name: "Workflow: Dependent Jobs"
on: ["push"]

jobs:
  job-1:
    runs-on: "ubuntu-latest"
    steps:
      - name: "step A"
        run: echo "Hello World"
  job-2:
    runs-on: "ubuntu-latest"
    steps:
      - name: "step B"
        run: echo "Yes"
        
        
